#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

if [ ! -d "/var/www/html/system/session/" ]; then
	mkdir /var/www/html/system/session/
	cp -r /var/www/html/systemdefault/* /var/www/html/system/
fi

chown www-data:www-data /var/www/html/system/session/
chown www-data:www-data /var/www/html/system/Backup/
chown www-data:www-data /var/www/html/system/DBData/Installation.pfdb.php
#chown www-data:www-data /var/www/html/system/specifics/

exec "$@"
